# Generated by Django 4.2.10 on 2024-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_reservation_is_reserving_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mail',
            field=models.EmailField(default='default@com.mx', max_length=254),
            preserve_default=False,
        ),
    ]
