# Generated by Django 4.2.10 on 2024-03-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_reservation_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adults_tickets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='child_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
