# Generated by Django 4.2.10 on 2024-03-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_reservation_adults_tickets_reservation_child_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_will_assist',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
